#
# COPYRIGHT Ericsson 2022
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

documents:
  # document name (used as name of the output file)
  - name: User_Guide
    # file names of files to be packaged (main md file and pictures)
    files:
      - ../doc/User_Guide/User_Guide.md
      - ../doc/User_Guide/Architecture_Diagram_KMSAgent.png
      - ../doc/User_Guide/Deployment_Diagram_KMSAgent.png